name: Java8

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
